vim.g.mapleader = " "
vim.o.emoji = true
vim.o.nu = true
vim.o.relativenumber = true
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.softtabstop = 2
vim.o.expandtab = true
vim.o.autoindent = true
vim.o.smartindent = true
vim.o.wrap = true
vim.o.swapfile = false
vim.o.backup = false
vim.o.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.o.undofile = true
vim.opt.incsearch = true
vim.opt.termguicolors = true
vim.opt.background = "dark"
vim.opt.clipboard:append("unnamedplus")
vim.opt.hlsearch = true
vim.opt.mouse = "a"
vim.o.splitright = true
vim.o.splitbelow = true
vim.g.editorconfig = true
